---
# tasks file for nginx

- name: Clean du serveur web nginx
  yum:
   name: nginx
   state: absent

- name: installation du dépot epel-release
  yum:
   name: epel-release
   state: present
   
- name: installation du serveur web nginx
  yum:
   name: nginx
   state: present

- name: "création de l'arborescence html pour les sites {{ sites }}"
  file:
    path: /var/www/{{ item }}/html
    owner: root
    group: root
    mode: 0755
    recurse: true
    state: directory
  loop:
    "{{ sites }}"

- name: "Création des fichiers index.html pour les {{ sites }}"
  template:
    src: index.html.j2
    dest: /var/www/{{ item }}/html/index.html
    mode: 0755
  loop:
   "{{ sites }}"

- name: "création de l'arborescence pour les sites disponibles et actifs"
  file:
    path: /etc/nginx/sites-{{ item }}
    owner: root
    group: root
    mode: 0755
    recurse: true
    state: directory
  loop:
   - available
   - enabled
- name: Configuration de nginx.conf
  blockinfile:
    path: /etc/nginx/nginx.conf
    insertbefore: "^# Settings"
    content: |
       "        include /etc/nginx/sites-enabled/*.conf;"
       "         server_names_hash_bucket_size 64;"

- name: "Configuration des sites {{ sites }}"
  template:
    src: sites.conf.j2
    dest: "/etc/nginx/sites-available/{{ item }}.conf"
  loop:
    "{{ sites }}"

- name: "activation des sites web {{ sites }}"
  file:
    src: /etc/nginx/sites-available/{{ item }}.conf
    dest: /etc/nginx/sites-enabled/{{ item }}.conf
    state: link
  loop:
    "{{ sites }}"
  notify: start_nginx 
  
  
  ## Serveur de base de données

- name: ajout dépot epel-release
   yum:
    name: epel-release
    state: present

- name: Installation MariaDB
  yum:
    name:
     - mariadb-server
     - python2-PyMySQL 

    state: present

- name: Start et activation MariaDB
  systemd:
    name: mariadb
    state: started
    enabled: yes

- name: Création fichier client
  copy:
    dest: /root/my.cnf
    content: |
      [client]
      user=root
      password= ""
  
- name: Upload sql table config
  template:
   src: table.sql.j2
   dest: /tmp/table.sql

- name: Insert table sql
  mysql_db:
   name: "{{ mysql_dbname }}"
   state: present
   login_user: root
   login_password: ""
   state: import
   target: /tmp/table.sql
